### ISSUE TITLE
Component/View for adding and filling cinema halls with seats (AdminPanel)

### ISSUE THREAD

**Issue by OlexTix** [OlexTix/FanFlix#16]
Adding new records (seats in Seats table) in our database is a very long and excruciating task, so it is a priority to make it more convenient and easier for us to do that. A new component is needed with some basic seats editing (adding seats with a click of a button, seats row adjusting etc).
Deadline- 24.05.2023
ABSOLUTE DEADLINE- before our last meeting

**Comment by OlexTix** [comment]
Yes

**Comment by piekny27** [comment]
https://nonsa.pl/wiki/Bo_tak
